sudo: required
dist: trusty
language: python
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - MAJ_VERSION="1.13"
  foreman:
  - IMAGE_NAME=foreman-docker
  - CONTAINER_PATH=foreman
  puppet:
  - CONTAINER_PATH=puppetmaster
  - IMAGE_NAME=puppetmaster-docker
install: true
script:
- cd $CONTAINER_PATH
- docker build -t readytalk/$IMAGE_NAME:$MAJ_VERSION.$TRAVIS_BUILD_NUMBER-$COMMIT
  .
- docker images
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push readytalk/$IMAGE_NAME:$MAJ_VERSION.$TRAVIS_BUILD_NUMBER-$COMMIT
notifications:
  email: false
