apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "foreman.fullname" . }}
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
spec:
  replicas: {{ .Values.foreman.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "foreman.name" . }}
      release: {{ .Release.Name }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "foreman.name" . }}
        release: {{ .Release.Name }}
        component: server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.foreman.image.repository }}:{{ .Values.foreman.image.tag }}"
          imagePullPolicy: {{ .Values.foreman.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.foreman.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /etc/nginx/sites-enabled/foreman-nginx.conf
              name: config
              subPath: foreman-nginx.conf
            - mountPath: /etc/foreman/database.yml
              name: config
              subPath: database.yml
          resources:
{{ toYaml .Values.foreman.resources | indent 12 }}
    {{- with .Values.foreman.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.foreman.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.foreman.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "foreman.fullname" . }}
