{{ if .Values.puppet.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "foreman.fullname" . }}-puppetdb
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puppetdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "foreman.name" . }}
      release: {{ .Release.Name }}
      component: puppetdb
  template:
    metadata:
      labels:
        app: {{ template "foreman.name" . }}
        release: {{ .Release.Name }}
        component: puppetdb
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres-puppetdb
          image: "{{ .Values.puppetdb.postgres.image.repository }}:{{ .Values.puppetdb.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.puppetdb.postgres.image.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.puppetdb.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.puppetdb.postgres.password }}
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_DB
              value: {{ .Values.puppetdb.postgres.dbName }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: puppetdb
        - name: {{ .Chart.Name }}-puppetdb
          image: "{{ .Values.puppetdb.image.repository }}:{{ .Values.puppetdb.image.tag }}"
          imagePullPolicy: {{ .Values.puppetdb.image.pullPolicy }}
          ports:
            - name: puppetdb
              containerPort: 8080
              protocol: TCP
            - name: puppetdb-ssl
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/puppetdb/conf.d/database.ini
              name: config
              subPath: database.ini
            - mountPath: /etc/puppetdb/conf.d/jetty.ini
              name: config
              subPath: jetty.ini

    {{- with .Values.puppetdb.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.puppetdb.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.puppetdb.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "foreman.fullname" . }}-puppetdb
        - name: puppetdb
          persistentVolumeClaim:
            claimName: {{ template "foreman.fullname" . }}-puppetdb
{{- end}}
