{{- if .Values.puppetdb.ingress.enabled -}}
{{- $fullName := include "foreman.fullname" . -}}
{{- $servicePort := .Values.puppetdb.service.externalPort -}}
{{- $ingressPath := .Values.puppetdb.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-puppetdb
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.puppetdb.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.puppetdb.ingress.tls }}
  tls:
  {{- range .Values.puppetdb.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.puppetdb.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-puppetdb
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
