{{ if .Values.utilitypod.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "foreman.fullname" . }}-utility
  labels:
    app: {{ template "foreman.name" . }}
    chart: {{ template "foreman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "foreman.name" . }}
      release: {{ .Release.Name }}
      component: utility
  template:
    metadata:
      labels:
        app: {{ template "foreman.name" . }}
        release: {{ .Release.Name }}
        component: utility
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.utilitypod.image.repository }}:{{ .Values.utilitypod.image.tag }}"
          imagePullPolicy: Always
          resources:
            request:
              cpu: 10m
              memory: 1024Mi
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "foreman.fullname" . }}-utility
{{- end}}
